### ISSUE TITLE
Error 1013 when accessing panel for class in Windows built EXE

### ISSUE THREAD

**Issue by justiceb** [LogMANOriginal/LabVIEW-Composition#12] opened 2021-08-29 17:35 UTC
Is this library theoretically supposed to work in Windows-built EXEs?  Or only in the development environment?
I just built a Windows EXE, and I'm getting the following error when attempting to get class private data:

error code 1013
Property Node (arg 1) in BlueEventLog.lvlib:Demo.vi
<APPEND>
The front panel for <b><MYCLASSPATH>\Child.lvclass\Child.ctl</b> could not be loaded but is required by this property or method.

To be clear, I am only getting this error when running as an EXE.  The error does not occur when I run this in the development environment.
I dove down into the code a bit, and I can confirm that the error pops out here:
![image](https://user-images.githubusercontent.com/7429922/131259815-1a694531-1053-4563-a036-8ce94690f0d2.png)

More specifically, the error occurs when attempting to get a reference to the class front panel.
(Note that I modified your code slightly to ensure that the error pops out at this property, and not the Library.version property.)
So, it seems to me that the LabVIEW application builder compiler is NOT including the front panel of the class when building.  If that's true, then this methodology here won't work for EXEs.

Thoughts?  Am I missing something?
Thanks!

**Comment by justiceb** [comment] 2021-08-29 17:36
Oh, and to be clear, I'm testing with LabVIEW 2020 SP1 32-bit

**Comment by LogMANOriginal** [comment] 2021-08-31 12:15
Yes it is supposed to work in binaries. Thanks for reporting this issue, I'll look into it.

**Comment by LogMANOriginal** [comment] 2021-08-31 13:11
There are runtime tests for this repository including classes. I played with different build settings and classes but everything seems to be working just fine (both in 2017 and 2020).

Is there anything special about your class?
Can you provide a sample that consistently fails for you?

**Comment by justiceb** [comment] 2021-08-31 15:31
Let me dig into this a bit and see if I can share something here in a reproducible manner.

**Comment by justiceb** [comment] 2021-09-02 19:48
[composition.zip](https://github.com/LogMANOriginal/LabVIEW-Composition/files/7101374/composition.zip)

apologies for the delay.
I've attached a zip file with LV2020 code.
Source code runs fine, but the built EXE here expresses the same issue mentioned above.

**Comment by LogMANOriginal** [comment] 2021-09-03 05:58
Thanks a lot, this is very helpful. I can confirm this issue happening on my machine with your code. One peculiar thing is that it can find the .ctl file in memory and opens a reference without any issues, but then returns an error when attempting to access the front panel. My own tests don't have this issue, so something must be different.

I also rebuild your test case from scratch with a brand new project and had the same issue. Maybe something is broken when installing with VIPM. I'll keep you posted.

I'll also address the error wiring, now that we have an actual test case :smile:

**Comment by LogMANOriginal** [comment] 2021-09-03 15:55
I found a solution. There were actually multiple issues:

- Decompose LabVIEW Object did not pass errors from SubVIs to the caller. Fixed via e7447e1
- Internal caching was implemented incorrectly, which resulted in errors being silently dropped on the second call (because items were added to the cache even if they failed to load). Fixed via 3a5400e
- LabVIEW sometimes (but not always?) removes the front panel of private data controls. The runtime tests implemented in this repository (see Composition.Tests/Main.vi) actually didn't throw an error until I unchecked the **Use fast file format** option.

Finally, to address this issue, instead of accessing the front panel directly, the library now uses the [Connector Pane:Data Type property](https://zone.ni.com/reference/en-XX/help/371361R-01/lvscript/vi_connector_pane058datatype/), which is a scripting function that is also available in RTE. This fixes the issue on my computer (also with your sample project).

Unfortunately this opened up a new issue where the returned data does not include the default value of the class. I assume that this  is not an issue for you right now but I'll fix that before publishing a new release.

Find attached a pre-release with the above fixes. Let me know if it works for you (remove ".zip" suffix after download).

[pnr_lib_labview_composition-1.2.4.20.vip.zip](https://github.com/LogMANOriginal/LabVIEW-Composition/files/7107151/pnr_lib_labview_composition-1.2.4.20.vip.zip)

**Comment by LogMANOriginal** [comment] 2021-09-04 17:26
Here is another version that also returns the default value of objects. It utilizes 'Get Mutation History' to extract object information, which also simplifies ancestor lookup. See 4eb518b for more details.

Same as before, please let me know if this works for you.
[pnr_lib_labview_composition-1.3.0.21.vip.zip](https://github.com/LogMANOriginal/LabVIEW-Composition/files/7110243/pnr_lib_labview_composition-1.3.0.21.vip.zip)

**Comment by justiceb** [comment] 2021-09-08 16:29
Ok, I feel dumb for asking this, but how do I unzip this into a vip file?  It keeps unzipping into a folder

**Comment by LogMANOriginal** [comment] 2021-09-08 16:46
It's already a .vip, just remove the .zip suffix. package.vip.zip should become package.vip

**Comment by justiceb** [comment] 2021-09-08 17:12
The mutation history option is interesting.  I'll have to think about that for a moment.
Mutation history has a few caveats.  For example, mutation history for a class doesn't update if a contained typedef is changed.  Example:
1) create typedef cluster
2) add typedef'd cluster to a class private data
3) change typedef cluster... observe that class mutation history doesn't change

This might be very confusing to a user of this library

**Comment by justiceb** [comment] 2021-09-08 17:21
![image](https://user-images.githubusercontent.com/7429922/132555260-34dec8d2-ac3e-46b8-8d27-9297549fab45.png)

does this code really not work in runtime?  I thought that this was runtime same, but maybe I was mistaken.

**Comment by justiceb** [comment] 2021-09-08 17:29
Also, I'm not sure if this is RTE compatible, but this exists and might possibly be helpful for getting path to the class hierarchy:
C:\Program Files (x86)\National Instruments\LabVIEW 2020\vi.lib\Utility\LVClass\Read Class Ancestry Without Loading.vi

**Comment by LogMANOriginal** [comment] 2021-09-08 18:05
> 1. create typedef cluster
> 2. add typedef'd cluster to a class private data
> 3. change typedef cluster... observe that class mutation history doesn't change

You have to apply changes in order to work with the class, otherwise it reports an error: "The control VI is not broken but has changes that have not been applied." Once changes are applied, a record is added to the mutation history. Am I doing it wrong?

> does this code really not work in runtime?

Unfortunately no. It will always return void. I believe that the private data control is considered a strict typedef and the `Control Value:Get All` method does not support them: https://zone.ni.com/reference/en-XX/help/371361R-01/lvprop/vi_get_all_cont_valuvrnt/

> Also, I'm not sure if this is RTE compatible, but this exists and might possibly be helpful for getting path to the class hierarchy:
C:\Program Files (x86)\National Instruments\LabVIEW 2020\vi.lib\Utility\LVClass\Read Class Ancestry Without Loading.vi

It does not work in RTE, unfortunately. Another nugget that would have made things much easier.

**Comment by justiceb** [comment] 2021-09-08 18:10
Ahh, I forgot about that popup dialogue for applying changes.  That might be enough to solve this.
Let me play with this a bit.  The problem statement is the same... can a typedef'd item in a class private data change without causing the class to create a new mutation history entry?  If yes, then that is problematic for this approach I think

**Comment by LogMANOriginal** [comment] 2021-09-08 18:37
Now that I think about it, this shouldn't be possible. There are native functions that rely on class mutation history to unflatten objects from string. If there was a way to change the type without affecting mutation history, it would affect all of these functions and therefore qualify as a bug.

Here is an article that summarizes how changes to the private data control affect mutation history: https://www.ni.com/en-us/support/documentation/supplemental/07/preserving-labview-class-data.html

>"Any edit that changes the data type of the private data cluster bumps the version number of Alpha."

> "Changing the default value of any elements of the private data cluster bumps the version number of Alpha."

**Comment by justiceb** [comment] 2021-09-08 19:51
oh wow, you're right.  I just tried:
1) close class
2) modify typedef, save/close
3) reopen class

The class then automatically adds the new mutation entry and also shows the unsaved changes as being the typedef change:
![image](https://user-images.githubusercontent.com/7429922/132575965-3afda73d-40af-420d-9161-93b5fa8a73f3.png)

**Comment by LogMANOriginal** [comment] 2022-01-21 16:09
Version 1.3.0 is finally released 🎉

**Closed by LogMANOriginal** 2022-01-21 16:09 UTC
Labels: bug

**Comment by felipefoz** [comment] 2022-01-29 18:26
> Unfortunately no. It will always return void. I believe that the private data control is considered a strict typedef and the Control Value:Get All method does not support them: https://zone.ni.com/reference/en-XX/help/371361R-01/lvprop/vi_get_all_cont_valuvrnt/

Hey, I might be late for the talk. But reading this post, I have a interesting point to make. This code should work on RTE:

Instead of using the Path for opening VI reference, I use a string, and I directly call the ctl. It always worked here in a built application. It is also possible getting the version.

![Read from Private Data](https://user-images.githubusercontent.com/63814202/151671867-e8f8e8d6-86f5-4dac-8426-79d66a1d488e.png)

Example: Class1.lvlib:Class1.lvclass. You would call Class1.lvlib:Class1.lvclass:Class1.ctl.

This case although, it assumes the constant is in the BD, I believe, I haven't tested properly with dynamic loading of classes.

**Comment by LogMANOriginal** [comment] 2022-02-01 18:38
You are right, my statement above is wrong. The code didn't work in built applications because of the parent lookup. Here is the reason:

![image](https://user-images.githubusercontent.com/5776685/152028004-06445b63-e04c-46ea-ba79-bc727eac642a.png)

It utilizes linker info, which isn't available in built applications. That code resided in the VI marked below.

![image](https://user-images.githubusercontent.com/5776685/152028877-172a0ef3-bf41-4c7c-822b-62a07834aae9.png)

Reading the library version and control data did actually work and was used in earlier versions of this library (see original post). Now it uses the mutation history to grab the entire class hierarchy in one go, which is much simpler.

Hope this clarifies things. Sorry for the confusion.

**Comment by felipefoz** [comment] 2022-02-04 10:34
No worries. 

I was just experimenting other days on different ways of reading, and I crossed to this post, then it caused me do some testing also on my side.

Congrats, and keep the good work with this project.
